### ISSUE TITLE
Error 500 when attempting to save vCenter User Password

### ISSUE THREAD

**Issue by seanpdiaz** [blink-zero/deployaroo#8]
When trying to save the credentials for vCenter server in the UI the server responds with "Server error. Something went wrong. Please try again later."

This occurs when running the app on a linux system without docker following the instructions in documentation.

<img width="636" alt="Screenshot 2024-07-13 at 12 55 07 AM" src="https://github.com/user-attachments/assets/4df6a806-c387-4179-bec8-adf2a1fd22b7">

[app.log](https://github.com/user-attachments/files/16201314/app.log)

**Comment by blink-zero** [comment]
I think this issue is because the secret and/or encryption key have not been set in the config.py or as env variables - if you are running directly as python3 run.py.

Steps to fix that issue.

Run 'python3 ./generate_encryption_key.py'

Use the value you get from this with one of the two options below:

Option 1:
(recommended)

Set environment variables for:
- ENCRYPTION_KEY
- SECRET_KEY

'export ENCRYPTION_KEY=generatedvalue'
'export SECRET_KEY=generatedvalue'

Option 2:

In ./apps/config.py

Update the following values with the values generated.

default_secret_key 
and
default_encryption_key

_________

I apologize for not having the doco mention this.
I will update very soon.

Note: I usually just run the generate script twice and use one for secret and another for encryption.

Please let me know if this works for you.

**Comment by seanpdiaz** [comment]
You were absolutely correct, I had put the encryption keys in the wrong location. This was definitely my bad, thank you for the quick response.

**Incorrect:**
````
SECRET_KEY = os.environ.get('JRA0jNpvCh_6vyc0dpALakogbzMTSnYNa9EgmBbEMQo=') or 'default_secret_key'
ENCRYPTION_KEY = os.environ.get('AAxYED6wfx26Nj2RibQGkDD14QlO4c7HQD-oR87w-MI=') or 'default_encryption_key'
````

**Correct:**
````
SECRET_KEY = os.environ.get('SECRET_KEY') or '4TkjnX8yI-PdT7Kk0He1KJOKlzfLb1pt0c0ioTMH038='
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY') or '0pG9wRD7NKLBFhL7fAIU-a8lDIINXTtZ3PQGI6O8ac0='
````
